-- Supabase SQL for Temporary Payment Storage (Task 3.5) - Corrected

-- 1. Create the temporary_payments table
CREATE TABLE public.temporary_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address TEXT NOT NULL,
  charge_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add index for efficient querying
CREATE INDEX idx_temporary_payments_ip_address ON public.temporary_payments (ip_address);
-- Add index for efficient cleanup based on creation time
CREATE INDEX idx_temporary_payments_created_at ON public.temporary_payments (created_at);

-- Enable Row Level Security (RLS)
ALTER TABLE public.temporary_payments ENABLE ROW LEVEL SECURITY;

-- Policies: Allow service_role full access, restrict others
-- (Adjust based on whether API routes use anon or service key for inserts/reads)
CREATE POLICY "Allow service_role full access" ON public.temporary_payments
  FOR ALL
  USING (TRUE)
  WITH CHECK (TRUE);

-- Optional: Allow authenticated users to read their own recent entries if needed (unlikely needed here)
-- CREATE POLICY "Allow users to read their recent entries" ON public.temporary_payments
--   FOR SELECT
--   USING (auth.role() = 'authenticated' AND ip_address = <function_to_get_current_request_ip()>); -- IP check is tricky in policies

-- 2. Enable pg_cron extension (if not already enabled)
-- Run this in the Supabase SQL Editor under Database > Extensions
-- CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;

-- 3. Schedule the cleanup job using pg_cron
-- This job runs every minute to delete entries older than 15 minutes.
-- Run this in the Supabase SQL Editor:
-- SELECT cron.schedule(
--   'delete-expired-temp-payments',
--   '* * * * *', -- Run every minute
--   $$
--   DELETE FROM public.temporary_payments
--   WHERE created_at < NOW() - INTERVAL '15 minutes';
--   $$
-- );

-- To unschedule the job (if needed):
-- SELECT cron.unschedule('delete-expired-temp-payments');

-- Note: Ensure your Supabase project has pg_cron enabled.
-- You need to run the CREATE EXTENSION and SELECT cron.schedule parts manually in the Supabase SQL editor.

